version: '3.9'
services:
  app:
    image: 'lukemb123/docker-spring-boot:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    hostname: "172.30.16.1"
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - ./data/etc/gitlab:/etc/gitlab
      - ./data/var/opt/gitlab:/var/opt/gitlab
      - ./data/var/log/gitlab:/var/log/gitlab

  gitlab-runner:
    container_name: runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./data/etc/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock